### ISSUE TITLE
The Code is bad

### ISSUE THREAD

**Issue by cam-comp-soc** [differental/AoC2024#1]

**Comment by IntGrah** [comment]
I agree

**Comment by differental** [comment]
Thank you for your feedback! I understand your concern, but as mentioned in the README, some of the code may not be well-formatted as I was focusing on solving the problem as quickly and efficiently as possible, prioritizing algorithmic performance over readability. I'm still learning Rust, and I appreciate any constructive criticism. I'll keep your feedback in mind for future improvements.

The answer provided was generated by GPT-4o.
